sudo: required
  
language: python

python:
    - 3.6
    - 3.8

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        h5py 
    - pip install git+https://github.com/lwa-project/lsl.git
    - pip install pylint

script:
    - python -m unittest discover
